- name: Setup server
  hosts: all
  become: yes
  tasks:
    - name: Create ansible-worker
      ansible.builtin.user:
        name: ansible-worker
        state: present

    - name: Install git
      ansible.builtin.apt:
        name: git
        state: present

    - name: Copy SSH key
      ansible.builtin.copy:
        src: ssh_keys/
        dest: /home/ansible-worker/.ssh/
        owner: ansible-worker
        group: ansible-worker
        mode: 0600

    - name: Clone repository
      ansible.builtin.git:
        repo: "https://github.com/iphilka/stud-template.git"
        dest: "/home/ansible-worker/www/stud-template"
        update: no
        clone: yes

    - name: Change file index.html
      ansible.builtin.copy:
        src: index.html
        dest: /home/ansible-worker/www/stud-template/index.html
        owner: ansible-worker
        group: ansible-worker
        mode: 0644

    - name: permissions for read ansible-worker
      ansible.builtin.file:
        path: /home/ansible-worker
        owner: ansible-worker
        group: ansible-worker
        mode: "0755"
        recurse: yes

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Copy Nginx config file in sites-available
      copy:
        src: config_file/ansible.iphilka.ru.conf
        dest: /etc/nginx/sites-available/

    - name: Create symbol link in sites-enabled
      file:
        src: /etc/nginx/sites-available/ansible.iphilka.ru.conf
        dest: /etc/nginx/sites-enabled/ansible.iphilka.ru.conf
        state: link